### ISSUE TITLE
Novo canal Igor Lucci

### ISSUE THREAD

**Issue by igorlucci** [ofabrizio/estudosBR#3]
| Nome | IGOR LUCCI
| Youtube | https://www.youtube.com/channel/UCJ5LEk3rAjd2U7N01VqQy5w
| Linkedin | https://www.linkedin.com/in/igorlucci/
| Site | https://igorlucci.carrd.co/
| Tem curso pago? | https://www.udemy.com/course/se-torne-um-engenheiros-de-dados-com-igor-lucci/learn/lecture/30865184#overview
| Tecnologias | Python, Google Cloud, Azure, Delta, Databricks, Data Factory, SQL
| Livros | nao
| Semana de Bootcamp? | em breve

**Comment by ofabrizio** [comment]
Boa! Adicionado! =)
